### ISSUE TITLE
iOS wireframes

### ISSUE THREAD

**Issue by jayceazua** [project-fashion/docs#4]

**Comment by jayceazua** [comment]
![birdseyeview](https://user-images.githubusercontent.com/24749332/52467063-0ba4f100-2b39-11e9-9647-b094a700d69c.png)

**Comment by jayceazua** [comment]
![birdseyeview](https://user-images.githubusercontent.com/24749332/52467095-28412900-2b39-11e9-9a02-f7ade9d81480.png)

**Comment by jayceazua** [comment]
@elgrian darn I'm trying to upload it here but it ain't working :/

**Comment by elgrian** [comment]
I'll fix it. I saved it as a png but I guess Photoshop things sometimes
still show up as .psd so I'll fix this tomorrow

**Comment by jayceazua** [comment]
@elgrian alright let me know once complete

**Comment by jayceazua** [comment]
<img width="1678" alt="screen shot 2019-02-11 at 11 39 28 pm" src="https://user-images.githubusercontent.com/24749332/52619470-8da55a80-2e56-11e9-9b01-7a06a7679bc4.png">
